name: Maven CI/CD

on:
 push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5.0.0
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v4.7.1
      with:
        java-version: '21'
        distribution: 'temurin'
        architecture: x64

    - name: Test project with Maven
      run: mvn -B test --file pom.xml
